# Generated by Django 3.0.7 on 2020-12-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.DateTimeField(default='2000-01-01')),
                ('booking_date', models.DateTimeField(default='2000-01-01')),
                ('name', models.TextField()),
                ('address', models.TextField(default='')),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.Player')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
